const BASE_W = 'https://en.wikipedia.org/wiki/Special:FilePath/';

export const deck = [
  { id:'maj0',  name:'The Fool',           img:BASE_W+'RWS_Tarot_00_Fool.jpg',             symbol:'🌟', type:'Major',    keywords:'New beginnings, innocence, adventure, free spirit',           up:'Something new and exciting is starting. Take the leap — things will work out better than you expect.', rev:'You are jumping into something without thinking it through. Slow down and make a plan first.' },
  { id:'maj1',  name:'The Magician',       img:BASE_W+'RWS_Tarot_01_Magician.jpg',         symbol:'✦',  type:'Major',    keywords:'Willpower, desire, creation, manifestation',                  up:'You already have everything you need to succeed. Focus your energy and make it happen now.', rev:'You have the skills but are not using them properly. Watch out for people who are trying to trick you.' },
  { id:'maj2',  name:'The High Priestess', img:BASE_W+'RWS_Tarot_02_High_Priestess.jpg',   symbol:'🌙', type:'Major',    keywords:'Intuition, mystery, inner knowledge, unconscious mind',       up:'Trust your gut feeling — it is telling you something important right now. Do not ignore it.', rev:'You are out of touch with your instincts. Something is being hidden from you — look closer.' },
  { id:'maj3',  name:'The Empress',        img:BASE_W+'RWS_Tarot_03_Empress.jpg',          symbol:'🌿', type:'Major',    keywords:'Abundance, nurturing, nature, fertility, beauty',             up:'Good things are growing in your life. This is a great time for creativity, love, and new beginnings.', rev:'You feel stuck or drained. Take better care of yourself and stop ignoring your own needs.' },
  { id:'maj4',  name:'The Emperor',        img:BASE_W+'RWS_Tarot_04_Emperor.jpg',          symbol:'♛',  type:'Major',    keywords:'Authority, structure, a father figure, solid foundation',     up:'Take control of the situation. Strong leadership and a clear plan will bring you the results you want.', rev:'Someone is being too controlling, or you are being too rigid. Loosen up and be open to other ideas.' },
  { id:'maj5',  name:'The Hierophant',     img:BASE_W+'RWS_Tarot_05_Hierophant.jpg',       symbol:'⛪', type:'Major',    keywords:'Spiritual wisdom, religious beliefs, tradition, conformity',   up:'Follow the advice of someone you trust and respect. Traditional methods will work well for you now.', rev:'Rules and expectations feel limiting. It may be time to think for yourself and break from tradition.' },
  { id:'maj6',  name:'The Lovers',         img:BASE_W+'RWS_Tarot_06_Lovers.jpg',           symbol:'♡',  type:'Major',    keywords:'Love, harmony, relationships, values alignment, choices',     up:'A strong connection or important choice is ahead. Follow your heart — it will lead you in the right direction.', rev:'There is tension in a relationship or a tough decision making things difficult. Be honest with yourself.' },
  { id:'maj7',  name:'The Chariot',        img:BASE_W+'RWS_Tarot_07_Chariot.jpg',          symbol:'⚡', type:'Major',    keywords:'Control, willpower, success, action, determination',          up:'Keep pushing — you are on the right track and success is coming. Stay focused and do not give up.', rev:'You are losing control or going in the wrong direction. Stop and figure out what is pulling you off course.' },
  { id:'maj8',  name:'Strength',           img:BASE_W+'RWS_Tarot_08_Strength.jpg',         symbol:'🦁', type:'Major',    keywords:'Strength, courage, patience, control, compassion',            up:'You are stronger than you think. Handle this challenge calmly and with kindness instead of force.', rev:'You are doubting yourself too much. Do not let fear or low confidence stop you from moving forward.' },
  { id:'maj9',  name:'The Hermit',         img:BASE_W+'RWS_Tarot_09_Hermit.jpg',           symbol:'🕯️', type:'Major',    keywords:'Soul-searching, introspection, being alone, inner guidance',  up:'Take some quiet time alone to think things through. The answer you need is already inside you.', rev:'You are isolating yourself too much or refusing help that is right in front of you. Open up a little.' },
  { id:'maj10', name:'Wheel of Fortune',   img:BASE_W+'RWS_Tarot_10_Wheel_of_Fortune.jpg', symbol:'☸️', type:'Major',    keywords:'Good luck, karma, life cycles, destiny, a turning point',     up:'Things are about to change for the better. A lucky turn is on its way — get ready for it.', rev:'Bad luck or an unexpected setback is slowing you down. This phase will pass — hang in there.' },
  { id:'maj11', name:'Justice',            img:BASE_W+'RWS_Tarot_11_Justice.jpg',          symbol:'⚖️', type:'Major',    keywords:'Justice, fairness, truth, cause and effect, law',             up:'The truth will come out and fairness will be restored. Do the right thing and things will work in your favor.', rev:'Something feels unfair right now. Face the facts honestly — avoiding the truth will only make things worse.' },
  { id:'maj12', name:'The Hanged Man',     img:BASE_W+'RWS_Tarot_12_Hanged_Man.jpg',       symbol:'🔄', type:'Major',    keywords:'Pause, surrender, letting go, new perspectives, enlightenment',up:'Pause and look at things from a different angle. Sometimes waiting and letting go is the smartest move.', rev:'You are stuck because you refuse to change your view. Stop resisting and try a different approach.' },
  { id:'maj13', name:'Death',              img:BASE_W+'RWS_Tarot_13_Death.jpg',            symbol:'🌑', type:'Major',    keywords:'Endings, beginnings, change, transformation, transition',      up:'Something is ending, but it is making room for something much better. Let it go and welcome the new start.', rev:'You are holding onto something that is already over. Letting go is hard, but it is the only way to move on.' },
  { id:'maj14', name:'Temperance',         img:BASE_W+'RWS_Tarot_14_Temperance.jpg',       symbol:'💧', type:'Major',    keywords:'Balance, moderation, patience, purpose, meaning',             up:'Take it one step at a time and find balance in your daily life. Patience will get you where you want to go.', rev:'You are overdoing it in some area — too much stress, too much of one thing. Find your balance again.' },
  { id:'maj15', name:'The Devil',          img:BASE_W+'RWS_Tarot_15_Devil.jpg',            symbol:'🔗', type:'Major',    keywords:'Shadow self, attachment, addiction, restriction, sexuality',   up:'Something has a hold on you and it is holding you back. Recognize the pattern and take steps to break free.', rev:'You are starting to free yourself from something that was controlling you. Keep going — freedom is close.' },
  { id:'maj16', name:'The Tower',          img:BASE_W+'RWS_Tarot_16_Tower.jpg',            symbol:'⚡', type:'Major',    keywords:'Sudden change, upheaval, chaos, revelation, awakening',       up:'A sudden and unexpected change is coming. It will be shocking, but once the dust settles things will be clearer.', rev:'You can feel something falling apart. Try to prepare instead of pretending everything is fine.' },
  { id:'maj17', name:'The Star',           img:BASE_W+'RWS_Tarot_17_Star.jpg',             symbol:'⭐', type:'Major',    keywords:'Hope, faith, purpose, renewal, spirituality',                 up:'After a hard time, good things are on their way. Have hope — better days are truly coming for you.', rev:'You have lost hope or feel disconnected from what you want. Reconnect with what matters most to you.' },
  { id:'maj18', name:'The Moon',           img:BASE_W+'RWS_Tarot_18_Moon.jpg',             symbol:'🌕', type:'Major',    keywords:'Illusion, fear, the unconscious, intuition, confusion',       up:'Things are not as clear as they seem. Trust your gut and look past the confusion to find the real truth.', rev:'The fog is clearing. Hidden things are coming to light and your fears are starting to make sense.' },
  { id:'maj19', name:'The Sun',            img:BASE_W+'RWS_Tarot_19_Sun.jpg',              symbol:'☀️', type:'Major',    keywords:'Positivity, fun, warmth, success, vitality',                  up:'Great energy and happiness are coming your way. This is a time of success, joy, and confidence — enjoy it.', rev:'You are feeling low or unsure of yourself right now. The good energy will return — do not give up.' },
  { id:'maj20', name:'Judgement',          img:BASE_W+'RWS_Tarot_20_Judgement.jpg',        symbol:'🎺', type:'Major',    keywords:'Judgement, rebirth, inner calling, absolution, awakening',    up:'You are being called to step up and be your best self. This is your moment — answer it with confidence.', rev:'You are being too hard on yourself or ignoring a clear sign. Learn from the past and start fresh.' },
  { id:'maj21', name:'The World',          img:BASE_W+'RWS_Tarot_21_World.jpg',            symbol:'🌍', type:'Major',    keywords:'Completion, integration, accomplishment, travel, wholeness',   up:'You have reached a major milestone — be proud of how far you have come. A satisfying chapter is wrapping up.', rev:'Something feels unfinished. There is still one more step to take before you can truly call this done.' },
  { id:'w1',  name:'Ace of Wands',     img:BASE_W+'Wands01.jpg', symbol:'🔥', type:'Wands',     keywords:'Inspiration, new opportunities, growth, potential',              up:'A brilliant new idea or opportunity is arriving. Act on it fast — your energy and motivation are at their peak.', rev:'You have a great idea but something keeps getting in the way. Clear your head and try again when you are ready.' },
  { id:'w2',  name:'Two of Wands',     img:BASE_W+'Wands02.jpg', symbol:'🔥', type:'Wands',     keywords:'Future planning, progress, decisions, discovery',                 up:'You have a solid plan and a clear vision. This is the right time to take that first big step forward.', rev:'Fear of the unknown is holding you back. Play it safe for now and keep working on your confidence.' },
  { id:'w3',  name:'Three of Wands',   img:BASE_W+'Wands03.jpg', symbol:'🔥', type:'Wands',     keywords:'Progress, expansion, foresight, overseas opportunities',          up:'Your hard work is starting to pay off. Look ahead — bigger opportunities and growth are coming your way.', rev:'Progress is slower than expected. There may be delays or setbacks — stay patient and keep going.' },
  { id:'w6',  name:'Six of Wands',     img:BASE_W+'Wands06.jpg', symbol:'🔥', type:'Wands',     keywords:'Success, public recognition, progress, self-confidence',          up:'You are winning! Your efforts are being noticed and celebrated by others around you. Enjoy the recognition.', rev:'A win feels less satisfying than expected, or you are not getting the credit you deserve. Keep your head up.' },
  { id:'w8',  name:'Eight of Wands',   img:BASE_W+'Wands08.jpg', symbol:'🔥', type:'Wands',     keywords:'Movement, fast paced change, action, alignment, air travel',      up:'Things are moving fast and in the right direction. Act quickly and make the most of this momentum.', rev:'Things are not moving as fast as you want. Stay calm — the delays will not last much longer.' },
  { id:'c1',  name:'Ace of Cups',      img:BASE_W+'Cups01.jpg',  symbol:'💧', type:'Cups',      keywords:'Love, new relationships, compassion, creativity',                 up:'New love, strong emotions, or a creative spark is on its way. Open your heart to let it in.', rev:'You are closing yourself off emotionally. Try to let your guard down a little — something good wants in.' },
  { id:'c2',  name:'Two of Cups',      img:BASE_W+'Cups02.jpg',  symbol:'💧', type:'Cups',      keywords:'Unified love, partnership, mutual attraction',                     up:'A deep and caring connection is forming between you and someone special. Things feel balanced and good.', rev:'There is tension or a lack of balance in a relationship. Open, honest conversation is needed right now.' },
  { id:'c4',  name:'Four of Cups',     img:BASE_W+'Cups04.jpg',  symbol:'💧', type:'Cups',      keywords:'Meditation, contemplation, apathy, reevaluation',                 up:'Take a moment to think before acting. The answer you are looking for might already be right in front of you.', rev:'You have been too stuck in your head. A good opportunity is nearby — do not miss it by overthinking.' },
  { id:'c7',  name:'Seven of Cups',    img:BASE_W+'Cups07.jpg',  symbol:'💧', type:'Cups',      keywords:'Opportunities, choices, wishful thinking, illusion',               up:'You have many options in front of you, which is exciting. Just make sure to think clearly before choosing.', rev:'Too many choices are making you confused. Get clear on what you actually want before you decide anything.' },
  { id:'c10', name:'Ten of Cups',      img:BASE_W+'Cups10.jpg',  symbol:'💧', type:'Cups',      keywords:'Divine love, blissful relationships, harmony, alignment',          up:'Happiness and harmony in your relationships and home life are coming. This is a truly joyful time for you.', rev:'Something feels off in your closest relationships. Try to reconnect and talk about what is really going on.' },
  { id:'s1',  name:'Ace of Swords',    img:BASE_W+'Swords01.jpg',symbol:'💨', type:'Swords',    keywords:'Breakthroughs, new ideas, mental clarity, success, truth',        up:'A moment of clarity is coming. You will finally get a clear, honest answer to something that has confused you.', rev:'Your thinking is unclear right now. Wait before making big decisions — things will become clearer soon.' },
  { id:'s3',  name:'Three of Swords',  img:BASE_W+'Swords03.jpg',symbol:'💨', type:'Swords',    keywords:'Heartbreak, emotional pain, sorrow, grief, hurt',                 up:'You are dealing with pain or heartbreak. Let yourself feel it — healing truly does start with honesty.', rev:'You are slowly healing from something painful. The worst is behind you and things are getting better.' },
  { id:'s7',  name:'Seven of Swords',  img:BASE_W+'Swords07.jpg',symbol:'💨', type:'Swords',    keywords:'Betrayal, deception, getting away with something, stealth',       up:'Be careful — someone around you may not be completely honest with you. Watch what you share and with whom.', rev:'A lie or dishonest situation is about to come to light. It may be time to come clean about something too.' },
  { id:'s10', name:'Ten of Swords',    img:BASE_W+'Swords10.jpg',symbol:'💨', type:'Swords',    keywords:'Painful endings, deep wounds, betrayal, loss, crisis',            up:'A painful situation is finally ending. As hard as it is, this is the turning point — things only go up from here.', rev:'You are slowly recovering from a very difficult time. Take it one day at a time — you are getting there.' },
  { id:'p1',  name:'Ace of Pentacles', img:BASE_W+'Pents01.jpg', symbol:'🌱', type:'Pentacles', keywords:'A new financial or career opportunity, manifestation, abundance', up:'A new money or work opportunity is knocking on your door. Grab it — this is a solid chance to build something real.', rev:'A good opportunity slipped by, or you are not quite ready to act on one. Get your finances and plans in order.' },
  { id:'p5',  name:'Five of Pentacles',img:BASE_W+'Pents05.jpg', symbol:'🌱', type:'Pentacles', keywords:'Financial loss, poverty, lack mindset, isolation, worry',         up:'Times are tough financially or emotionally, but support is available. Do not be too proud to ask for help.', rev:'You are starting to recover from a hard financial or emotional period. Keep going — the worst is nearly over.' },
  { id:'p9',  name:'Nine of Pentacles',img:BASE_W+'Pents09.jpg', symbol:'🌱', type:'Pentacles', keywords:'Abundance, luxury, self-sufficiency, financial independence',      up:'You have worked hard and it is paying off. Enjoy the rewards of your effort — you have truly earned them.', rev:'You are overworking yourself or tying your self-worth to money. Remember that you are more than what you earn.' },
  { id:'p10', name:'Ten of Pentacles', img:BASE_W+'Pents10.jpg', symbol:'🌱', type:'Pentacles', keywords:'Wealth, financial security, family, long-term success, prosperity',up:'Long-term financial security and family happiness are within reach. The stable, fulfilling life you want is close.', rev:'Money or family tensions are causing stress. Have an honest conversation about shared goals and expectations.' },
];

export const deckMap = Object.fromEntries(deck.map(c => [c.id, c]));

export const zodiacTarotMap = {
  Aries: 'maj4', Taurus: 'maj5', Gemini: 'maj6', Cancer: 'maj7',
  Leo: 'maj8', Virgo: 'maj9', Libra: 'maj11', Scorpio: 'maj13',
  Sagittarius: 'maj14', Capricorn: 'maj15', Aquarius: 'maj17', Pisces: 'maj18',
};

export const zodiacTarotData = {
  Aries:       { value: 4,  name: 'The Emperor',      up: 'Authority, structure, a father figure, solid foundation, power.', rev: 'Domination, excessive control, lack of discipline, inflexibility.' },
  Taurus:      { value: 5,  name: 'The Hierophant',   up: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions.', rev: 'Personal beliefs, freedom, challenging the status quo.' },
  Gemini:      { value: 6,  name: 'The Lovers',       up: 'Love, harmony, relationships, values alignment, choices.', rev: 'Self-love, disharmony, imbalance, misaligned values.' },
  Cancer:      { value: 7,  name: 'The Chariot',      up: 'Control, willpower, success, action, determination.', rev: 'Self-discipline, opposition, lack of direction, aggression.' },
  Leo:         { value: 8,  name: 'Strength',         up: 'Strength, courage, patience, control, compassion.', rev: 'Inner strength, self-doubt, low energy, raw emotion.' },
  Virgo:       { value: 9,  name: 'The Hermit',       up: 'Soul-searching, introspection, being alone, inner guidance.', rev: 'Isolation, loneliness, withdrawal, rejection.' },
  Libra:       { value: 11, name: 'Justice',          up: 'Justice, fairness, truth, cause and effect, law.', rev: 'Unfairness, lack of accountability, dishonesty.' },
  Scorpio:     { value: 13, name: 'Death',            up: 'Endings, beginnings, change, transformation, transition.', rev: 'Resistance to change, personal transformation, inner purging.' },
  Sagittarius: { value: 14, name: 'Temperance',       up: 'Balance, moderation, patience, purpose, meaning.', rev: 'Imbalance, excess, self-healing, realignment.' },
  Capricorn:   { value: 15, name: 'The Devil',        up: 'Shadow self, attachment, addiction, restriction, sexuality.', rev: 'Releasing limiting beliefs, exploring dark thoughts, detachment.' },
  Aquarius:    { value: 17, name: 'The Star',         up: 'Hope, faith, purpose, renewal, spirituality.', rev: 'Lack of faith, despair, self-trust, disconnection.' },
  Pisces:      { value: 18, name: 'The Moon',         up: 'Illusion, fear, the unconscious, intuition, confusion.', rev: 'Release of fear, repressed emotion, inner confusion.' },
};

export const typeColors = {
  Major:    ['#0f1f3d', '#1a3a5c'],
  Wands:    ['#7b2d00', '#c45200'],
  Cups:     ['#0d3b6e', '#1565c0'],
  Swords:   ['#1a1a2e', '#424242'],
  Pentacles:['#1b4332', '#2d6a4f'],
};

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
