const BASE_W = 'https://upload.wikimedia.org/wikipedia/commons/';

export const deck = [
  { id:'maj0',  name:'The Fool',           img:BASE_W+'0/03/RWS_Tarot_00_Fool.jpg',               symbol:'🌟', type:'Major',    keywords:'New beginnings, innocence, adventure, free spirit',           up:'A leap of faith awaits. Embrace new beginnings with an open heart — the universe supports your journey.', rev:'Recklessness, risk-taking, a lack of direction or poor judgement clouding your path forward.' },
  { id:'maj1',  name:'The Magician',        img:BASE_W+'d/de/RWS_Tarot_01_Magician.jpg',           symbol:'✦',  type:'Major',    keywords:'Willpower, desire, creation, manifestation',                  up:'You have all the tools you need. Channel your focus and manifest your intentions into reality now.', rev:'Manipulation, poor planning, untapped talents or skills being used for the wrong purpose.' },
  { id:'maj2',  name:'The High Priestess',  img:BASE_W+'8/88/RWS_Tarot_02_High_Priestess.jpg',     symbol:'🌙', type:'Major',    keywords:'Intuition, mystery, inner knowledge, unconscious mind',       up:'Listen to your inner voice. Hidden truths are surfacing — trust your intuition above rational thought.', rev:'Secrets, disconnection from intuition, withdrawal or information being withheld from you.' },
  { id:'maj3',  name:'The Empress',         img:BASE_W+'d/d3/RWS_Tarot_03_Empress.jpg',            symbol:'🌿', type:'Major',    keywords:'Abundance, nurturing, nature, fertility, beauty',             up:'A time of growth and abundance. Nature and creativity flow freely — nurture what you love.', rev:'Creative block, dependence, smothering or neglect of self and others around you.' },
  { id:'maj4',  name:'The Emperor',         img:BASE_W+'c/c3/RWS_Tarot_04_Emperor.jpg',            symbol:'♛',  type:'Major',    keywords:'Authority, structure, a father figure, solid foundation',     up:'Take charge and establish order. Your leadership and determination will bring lasting, stable results.', rev:'Domination, excessive control, rigidity or an abuse of authority affecting your situation.' },
  { id:'maj5',  name:'The Hierophant',      img:BASE_W+'8/8d/RWS_Tarot_05_Hierophant.jpg',         symbol:'⛪', type:'Major',    keywords:'Spiritual wisdom, religious beliefs, tradition, conformity',   up:'Seek wisdom from tradition or a trusted mentor. Spiritual growth comes through learning and established systems.', rev:'Personal beliefs, freedom from convention, challenging institutions that no longer serve you.' },
  { id:'maj6',  name:'The Lovers',          img:BASE_W+'3/3a/TheLovers.jpg',                        symbol:'♡',  type:'Major',    keywords:'Love, harmony, relationships, values alignment, choices',     up:'A meaningful connection or important choice is at hand. Follow your heart with clear intention and purpose.', rev:'Self-love, disharmony, imbalance, misaligned values or a difficult decision weighing on you.' },
  { id:'maj7',  name:'The Chariot',         img:BASE_W+'9/9b/RWS_Tarot_07_Chariot.jpg',            symbol:'⚡', type:'Major',    keywords:'Control, willpower, success, action, determination',          up:'Press forward with confidence. Focus and determination will carry you through any obstacle in your path.', rev:'Self-discipline lacking, opposition, lack of direction or aggression undermining your progress.' },
  { id:'maj8',  name:'Strength',            img:BASE_W+'f/f5/RWS_Tarot_08_Strength.jpg',           symbol:'🦁', type:'Major',    keywords:'Strength, courage, patience, control, compassion',            up:'True power comes from within. Approach challenges with compassion and gentle strength rather than force.', rev:'Inner strength is being doubted, low energy, raw emotion or self-doubt holding you back.' },
  { id:'maj9',  name:'The Hermit',          img:BASE_W+'4/4d/RWS_Tarot_09_Hermit.jpg',             symbol:'🕯️', type:'Major',    keywords:'Soul-searching, introspection, being alone, inner guidance',  up:'Step back and look within. A period of quiet reflection will illuminate your path and reveal your truth.', rev:'Isolation, loneliness, withdrawal or rejection of the guidance being offered to you.' },
  { id:'maj10', name:'Wheel of Fortune',    img:BASE_W+'3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg',  symbol:'☸️', type:'Major',    keywords:'Good luck, karma, life cycles, destiny, a turning point',     up:'The wheel is turning in your favour. Embrace change — a new, fortunate cycle is beginning now.', rev:'Bad luck, resistance to change, breaking cycles or a turning point that feels beyond your control.' },
  { id:'maj11', name:'Justice',             img:BASE_W+'e/e0/RWS_Tarot_11_Justice.jpg',            symbol:'⚖️', type:'Major',    keywords:'Justice, fairness, truth, cause and effect, law',             up:'Balance and truth prevail. Act with integrity and the universe will restore harmony and equilibrium.', rev:'Unfairness, lack of accountability, dishonesty or consequences of past actions catching up.' },
  { id:'maj12', name:'The Hanged Man',      img:BASE_W+'2/2b/RWS_Tarot_12_Hanged_Man.jpg',        symbol:'🔄', type:'Major',    keywords:'Pause, surrender, letting go, new perspectives, enlightenment',up:'Let go and gain a new vantage point. Surrender opens doors that force alone cannot unlock.', rev:'Delays, resistance, stalling or an inability to release what is no longer serving you.' },
  { id:'maj13', name:'Death',               img:BASE_W+'d/d7/RWS_Tarot_13_Death.jpg',              symbol:'🌑', type:'Major',    keywords:'Endings, beginnings, change, transformation, transition',      up:'An ending makes way for powerful transformation. Release the old to welcome what is aligned with you now.', rev:'Resistance to change, personal transformation from within or fear of endings blocking your growth.' },
  { id:'maj14', name:'Temperance',          img:BASE_W+'f/f8/RWS_Tarot_14_Temperance.jpg',        symbol:'💧', type:'Major',    keywords:'Balance, moderation, patience, purpose, meaning',             up:'Find the middle path. Patience and balance bring the harmony, healing and integration you are seeking.', rev:'Imbalance, excess, self-healing needed or realignment of your priorities required now.' },
  { id:'maj15', name:'The Devil',           img:BASE_W+'5/55/RWS_Tarot_15_Devil.jpg',              symbol:'🔗', type:'Major',    keywords:'Shadow self, attachment, addiction, restriction, sexuality',   up:'Examine what binds you. Awareness of your patterns and shadow self is the first step to lasting freedom.', rev:'Releasing limiting beliefs, exploring dark thoughts, detachment from what no longer serves you.' },
  { id:'maj16', name:'The Tower',           img:BASE_W+'5/53/RWS_Tarot_16_Tower.jpg',              symbol:'⚡', type:'Major',    keywords:'Sudden change, upheaval, chaos, revelation, awakening',       up:'Unexpected change shakes the foundation — but what remains will be truer, stronger and more authentic.', rev:'Personal transformation, fear of change, averting disaster or a delayed upheaval building beneath.' },
  { id:'maj17', name:'The Star',            img:BASE_W+'d/db/RWS_Tarot_17_Star.jpg',               symbol:'⭐', type:'Major',    keywords:'Hope, faith, purpose, renewal, spirituality',                 up:'After the storm comes light. Hope, healing and inspiration flow toward you like starlight in darkness.', rev:'Lack of faith, despair, self-trust challenged or a disconnection from your sense of hope and purpose.' },
  { id:'maj18', name:'The Moon',            img:BASE_W+'7/7f/RWS_Tarot_18_Moon.jpg',               symbol:'🌕', type:'Major',    keywords:'Illusion, fear, the unconscious, intuition, confusion',       up:'Not all is as it seems. Trust your instincts and look beyond illusions to find the deeper truth beneath.', rev:'Release of fear, repressed emotion, inner confusion lifting or hidden truths coming to light.' },
  { id:'maj19', name:'The Sun',             img:BASE_W+'1/17/RWS_Tarot_19_Sun.jpg',                symbol:'☀️', type:'Major',    keywords:'Positivity, fun, warmth, success, vitality',                  up:'Radiant energy surrounds you. Confidence, clarity, joy and success are yours to embrace fully today.', rev:'Inner child, feeling down, overly optimistic or temporarily blocked from your natural joy and radiance.' },
  { id:'maj20', name:'Judgement',           img:BASE_W+'d/dd/RWS_Tarot_20_Judgement.jpg',          symbol:'🎺', type:'Major',    keywords:'Judgement, rebirth, inner calling, absolution, awakening',    up:'A moment of profound awakening. Answer your calling and step boldly and authentically into your purpose.', rev:'Self-doubt, inner critic, ignoring the call or refusing to learn the lessons being presented to you.' },
  { id:'maj21', name:'The World',           img:BASE_W+'f/ff/RWS_Tarot_21_World.jpg',              symbol:'🌍', type:'Major',    keywords:'Completion, integration, accomplishment, travel, wholeness',   up:'A cycle is beautifully complete. Celebrate how far you have come — wholeness and fulfilment are yours now.', rev:'Seeking personal closure, shortcuts being taken or an incomplete journey that requires more of your attention.' },
  { id:'w1',  name:'Ace of Wands',     img:BASE_W+'1/11/Wands01.jpg', symbol:'🔥', type:'Wands',     keywords:'Inspiration, new opportunities, growth, potential',              up:'A spark of inspiration ignites. Seize this creative energy and take decisive action toward your passion.', rev:'Delays, lack of motivation, weighed down or creative blocks preventing you from starting fresh.' },
  { id:'w2',  name:'Two of Wands',     img:BASE_W+'a/a3/Wands02.jpg', symbol:'🔥', type:'Wands',     keywords:'Future planning, progress, decisions, discovery',                 up:'You are standing at the threshold of possibility. Plan boldly and take the first courageous step forward.', rev:'Personal goals, inner alignment, fear of the unknown or playing it too safe with your ambitions.' },
  { id:'w3',  name:'Three of Wands',   img:BASE_W+'f/f9/Wands03.jpg', symbol:'🔥', type:'Wands',     keywords:'Progress, expansion, foresight, overseas opportunities',          up:'Your plans are already in motion. Look to the horizon — expansion and progress are heading your way.', rev:'Playing small, lack of foresight, unexpected delays or obstacles interrupting your momentum.' },
  { id:'w6',  name:'Six of Wands',     img:BASE_W+'3/38/Wands06.jpg', symbol:'🔥', type:'Wands',     keywords:'Success, public recognition, progress, self-confidence',          up:'Victory is yours. Public recognition arrives and your confidence inspires those around you to believe too.', rev:'Private achievement, personal definition of success or a fall from a position of pride.' },
  { id:'w8',  name:'Eight of Wands',   img:BASE_W+'e/e0/Wands08.jpg', symbol:'🔥', type:'Wands',     keywords:'Movement, fast paced change, action, alignment, air travel',      up:'Things are moving fast now. Swift action brings alignment — be ready to receive what is rushing toward you.', rev:'Delays, frustration, resisting change or losing momentum on something that needs consistent energy.' },
  { id:'c1',  name:'Ace of Cups',      img:BASE_W+'3/36/Cups01.jpg',  symbol:'💧', type:'Cups',      keywords:'Love, new relationships, compassion, creativity',                 up:'An outpouring of love and emotional energy. Open your heart — new connections and joy are arriving now.', rev:'Self-love, intuition, repressed emotions or creative blocks preventing your heart from opening.' },
  { id:'c2',  name:'Two of Cups',      img:BASE_W+'2/2f/Cups02.jpg',  symbol:'💧', type:'Cups',      keywords:'Unified love, partnership, mutual attraction',                     up:'A deep and meaningful connection is forming. Mutual understanding and emotional harmony define this bond.', rev:'Self-love, break-ups, disharmony or an imbalance of power or feeling in an important relationship.' },
  { id:'c4',  name:'Four of Cups',     img:BASE_W+'6/63/Cups04.jpg',  symbol:'💧', type:'Cups',      keywords:'Meditation, contemplation, apathy, reevaluation',                 up:'A time to pause and reflect. What is right in front of you may hold more value than what you are searching for.', rev:'Retreat, withdrawal, checking in with yourself or recognising an opportunity you previously overlooked.' },
  { id:'c7',  name:'Seven of Cups',    img:BASE_W+'a/a0/Cups07.jpg',  symbol:'💧', type:'Cups',      keywords:'Opportunities, choices, wishful thinking, illusion',               up:'Many possibilities appear before you. Get clear on what you truly want before making your choice today.', rev:'Alignment, personal values, overwhelmed by options or returning to clarity after confusion and illusion.' },
  { id:'c10', name:'Ten of Cups',      img:BASE_W+'8/8f/Cups10.jpg',  symbol:'💧', type:'Cups',      keywords:'Divine love, blissful relationships, harmony, alignment',          up:'Deep fulfilment in relationships and home life. True happiness and emotional harmony surround you now.', rev:'Disconnection, misaligned values, broken family dynamic or searching for the meaning of true happiness.' },
  { id:'s1',  name:'Ace of Swords',    img:BASE_W+'1/1a/Swords01.jpg',symbol:'💨', type:'Swords',    keywords:'Breakthroughs, new ideas, mental clarity, success, truth',        up:'A breakthrough arrives with clarity and truth. Cut through confusion — the answer you need is now clear.', rev:'Inner clarity, re-thinking decisions or a powerful idea that needs to be refined before it can emerge.' },
  { id:'s3',  name:'Three of Swords',  img:BASE_W+'d/d0/Swords03.jpg',symbol:'💨', type:'Swords',    keywords:'Heartbreak, emotional pain, sorrow, grief, hurt',                 up:'Painful truths surface. Acknowledge the grief — moving through it honestly leads to real healing and growth.', rev:'Negative self-talk, releasing pain, optimism returning or the healing of a deep emotional wound.' },
  { id:'s7',  name:'Seven of Swords',  img:BASE_W+'3/34/Swords07.jpg',symbol:'💨', type:'Swords',    keywords:'Betrayal, deception, getting away with something, stealth',       up:'Strategy and discretion are needed. Be mindful of who you trust — not everyone has honest intentions here.', rev:'Imposter syndrome, self-deceit, coming clean or finally acknowledging a truth you have been avoiding.' },
  { id:'s10', name:'Ten of Swords',    img:BASE_W+'9/90/Swords10.jpg',symbol:'💨', type:'Swords',    keywords:'Painful endings, deep wounds, betrayal, loss, crisis',            up:'A painful ending, but also the beginning of a new chapter. Rock bottom brings the clarity needed to rise again.', rev:'Recovery, regeneration, resisting an inevitable ending or finding the strength to survive a crisis.' },
  { id:'p1',  name:'Ace of Pentacles', img:BASE_W+'f/fd/Pents01.jpg', symbol:'🌱', type:'Pentacles', keywords:'A new financial or career opportunity, manifestation, abundance', up:'A new material opportunity presents itself. Plant this seed with intention — abundance and growth follow.', rev:'Lost opportunity, lack of planning, scarcity mindset or failing to act on a promising new beginning.' },
  { id:'p5',  name:'Five of Pentacles',img:BASE_W+'6/62/Pents05.jpg', symbol:'🌱', type:'Pentacles', keywords:'Financial loss, poverty, lack mindset, isolation, worry',         up:'A difficult time financially or spiritually. Help is available — look up and reach out to what supports you.', rev:'Recovery from financial loss, spiritual poverty ending or finding your strength after a period of hardship.' },
  { id:'p9',  name:'Nine of Pentacles',img:BASE_W+'8/8f/Pents09.jpg', symbol:'🌱', type:'Pentacles', keywords:'Abundance, luxury, self-sufficiency, financial independence',      up:'You have created something beautiful through your own hard work. Enjoy the abundance you have earned now.', rev:'Self-worth, over-investment in work, financial setbacks or a reminder that inner wealth matters most.' },
  { id:'p10', name:'Ten of Pentacles', img:BASE_W+'a/a7/Pents10.jpg', symbol:'🌱', type:'Pentacles', keywords:'Wealth, financial security, family, long-term success, prosperity',up:'Legacy and lasting abundance. The foundations you have built support not just you but those you love.', rev:'The dark side of wealth, family disputes, financial failure or instability beneath a surface of prosperity.' },
];

export const deckMap = Object.fromEntries(deck.map(c => [c.id, c]));

export const zodiacTarotMap = {
  Aries: 'maj4', Taurus: 'maj5', Gemini: 'maj6', Cancer: 'maj7',
  Leo: 'maj8', Virgo: 'maj9', Libra: 'maj11', Scorpio: 'maj13',
  Sagittarius: 'maj14', Capricorn: 'maj15', Aquarius: 'maj17', Pisces: 'maj18',
};

export const zodiacTarotData = {
  Aries:       { value: 4,  name: 'The Emperor',      up: 'Authority, structure, a father figure, solid foundation, power.', rev: 'Domination, excessive control, lack of discipline, inflexibility.' },
  Taurus:      { value: 5,  name: 'The Hierophant',   up: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions.', rev: 'Personal beliefs, freedom, challenging the status quo.' },
  Gemini:      { value: 6,  name: 'The Lovers',       up: 'Love, harmony, relationships, values alignment, choices.', rev: 'Self-love, disharmony, imbalance, misaligned values.' },
  Cancer:      { value: 7,  name: 'The Chariot',      up: 'Control, willpower, success, action, determination.', rev: 'Self-discipline, opposition, lack of direction, aggression.' },
  Leo:         { value: 8,  name: 'Strength',         up: 'Strength, courage, patience, control, compassion.', rev: 'Inner strength, self-doubt, low energy, raw emotion.' },
  Virgo:       { value: 9,  name: 'The Hermit',       up: 'Soul-searching, introspection, being alone, inner guidance.', rev: 'Isolation, loneliness, withdrawal, rejection.' },
  Libra:       { value: 11, name: 'Justice',          up: 'Justice, fairness, truth, cause and effect, law.', rev: 'Unfairness, lack of accountability, dishonesty.' },
  Scorpio:     { value: 13, name: 'Death',            up: 'Endings, beginnings, change, transformation, transition.', rev: 'Resistance to change, personal transformation, inner purging.' },
  Sagittarius: { value: 14, name: 'Temperance',       up: 'Balance, moderation, patience, purpose, meaning.', rev: 'Imbalance, excess, self-healing, realignment.' },
  Capricorn:   { value: 15, name: 'The Devil',        up: 'Shadow self, attachment, addiction, restriction, sexuality.', rev: 'Releasing limiting beliefs, exploring dark thoughts, detachment.' },
  Aquarius:    { value: 17, name: 'The Star',         up: 'Hope, faith, purpose, renewal, spirituality.', rev: 'Lack of faith, despair, self-trust, disconnection.' },
  Pisces:      { value: 18, name: 'The Moon',         up: 'Illusion, fear, the unconscious, intuition, confusion.', rev: 'Release of fear, repressed emotion, inner confusion.' },
};

export const typeColors = {
  Major:    ['#0f1f3d', '#1a3a5c'],
  Wands:    ['#7b2d00', '#c45200'],
  Cups:     ['#0d3b6e', '#1565c0'],
  Swords:   ['#1a1a2e', '#424242'],
  Pentacles:['#1b4332', '#2d6a4f'],
};

export function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
