export const zodiacInfoData = {
  Aries: {
    symbol: '♈', element: 'Fire', mode: 'Cardinal',
    planet: 'Mars', dates: 'Mar 21 – Apr 19', color: '#E53935',
    traits: ['Bold', 'Driven', 'Courageous', 'Enthusiastic', 'Independent'],
    shadow: ['Impulsive', 'Short-tempered', 'Impatient'],
    compatible: ['Leo', 'Sagittarius', 'Gemini', 'Aquarius'],
    lucky: [1, 9],
    description: 'Aries is the pioneer of the zodiac — bold, direct, and unstoppable when driven by passion. As the first sign, you carry an innate sense of new beginnings and the courage to act before others dare. Your energy is magnetic and your confidence infectious, but your greatest growth comes in learning that patience and strategy can amplify your power.',
  },
  Taurus: {
    symbol: '♉', element: 'Earth', mode: 'Fixed',
    planet: 'Venus', dates: 'Apr 20 – May 20', color: '#2E7D32',
    traits: ['Patient', 'Reliable', 'Sensual', 'Determined', 'Grounded'],
    shadow: ['Stubborn', 'Possessive', 'Resistant to change'],
    compatible: ['Virgo', 'Capricorn', 'Cancer', 'Pisces'],
    lucky: [2, 6],
    description: 'Taurus is the builder of the zodiac — patient, sensual, and deeply connected to the material world. Your steadiness is your greatest strength; you create beauty and stability wherever you root. The lesson for Taurus is releasing the grip on what was in order to receive what could be.',
  },
  Gemini: {
    symbol: '♊', element: 'Air', mode: 'Mutable',
    planet: 'Mercury', dates: 'May 21 – Jun 20', color: '#F57C00',
    traits: ['Curious', 'Witty', 'Adaptable', 'Communicative', 'Versatile'],
    shadow: ['Scattered', 'Inconsistent', 'Restless'],
    compatible: ['Libra', 'Aquarius', 'Aries', 'Leo'],
    lucky: [3, 5],
    description: 'Gemini is the communicator of the zodiac — curious, quick-minded, and endlessly adaptable. You see all sides of every story and your ability to connect ideas and people is genuinely remarkable. Your growth edge is learning to go deep rather than wide, to let one idea fully bloom.',
  },
  Cancer: {
    symbol: '♋', element: 'Water', mode: 'Cardinal',
    planet: 'Moon', dates: 'Jun 21 – Jul 22', color: '#0277BD',
    traits: ['Intuitive', 'Nurturing', 'Loyal', 'Empathetic', 'Protective'],
    shadow: ['Moody', 'Clingy', 'Over-sensitive'],
    compatible: ['Scorpio', 'Pisces', 'Taurus', 'Virgo'],
    lucky: [2, 7],
    description: 'Cancer is the nurturer of the zodiac — deeply intuitive, protective, and profoundly attuned to the emotional world. Your gift is creating safety and belonging for those you love. Your growth comes in learning that caring for yourself first is not selfishness — it is the source of your capacity to give.',
  },
  Leo: {
    symbol: '♌', element: 'Fire', mode: 'Fixed',
    planet: 'Sun', dates: 'Jul 23 – Aug 22', color: '#F9A825',
    traits: ['Confident', 'Generous', 'Warm', 'Creative', 'Charismatic'],
    shadow: ['Arrogant', 'Attention-seeking', 'Demanding'],
    compatible: ['Aries', 'Sagittarius', 'Gemini', 'Libra'],
    lucky: [1, 5],
    description: 'Leo is the performer of the zodiac — radiant, generous, and born to shine. Your warmth draws others in naturally and your courage to be fully yourself inspires everyone around you. The lesson for Leo is discovering that true power flows not from being seen, but from genuinely seeing others.',
  },
  Virgo: {
    symbol: '♍', element: 'Earth', mode: 'Mutable',
    planet: 'Mercury', dates: 'Aug 23 – Sep 22', color: '#558B2F',
    traits: ['Analytical', 'Precise', 'Diligent', 'Practical', 'Helpful'],
    shadow: ['Critical', 'Perfectionist', 'Overthinking'],
    compatible: ['Taurus', 'Capricorn', 'Cancer', 'Scorpio'],
    lucky: [5, 6],
    description: 'Virgo is the analyst of the zodiac — precise, dedicated, and driven by a genuine desire to improve things. Your eye for detail and capacity for service are extraordinary gifts when turned outward with self-compassion. Your growth lies in embracing the beautifully imperfect as worthy of love.',
  },
  Libra: {
    symbol: '♎', element: 'Air', mode: 'Cardinal',
    planet: 'Venus', dates: 'Sep 23 – Oct 22', color: '#C2185B',
    traits: ['Diplomatic', 'Fair', 'Graceful', 'Social', 'Aesthetic'],
    shadow: ['Indecisive', 'Avoidant', 'People-pleasing'],
    compatible: ['Gemini', 'Aquarius', 'Leo', 'Sagittarius'],
    lucky: [6, 9],
    description: 'Libra is the diplomat of the zodiac — graceful, fair-minded, and deeply attuned to beauty and balance. You have a rare ability to see all sides and bring harmony to the most difficult situations. Your growth comes in learning that choosing yourself is not imbalance — it is the foundation of true fairness.',
  },
  Scorpio: {
    symbol: '♏', element: 'Water', mode: 'Fixed',
    planet: 'Pluto', dates: 'Oct 23 – Nov 21', color: '#6A1B9A',
    traits: ['Intense', 'Perceptive', 'Resilient', 'Strategic', 'Passionate'],
    shadow: ['Controlling', 'Jealous', 'Secretive'],
    compatible: ['Cancer', 'Pisces', 'Virgo', 'Capricorn'],
    lucky: [8, 9],
    description: 'Scorpio is the transformer of the zodiac — magnetic, perceptive, and drawn to the depths of every experience. Your emotional intensity and capacity for transformation are unparalleled forces when directed with intention. Your growth is in learning that true power comes from vulnerability, not control.',
  },
  Sagittarius: {
    symbol: '♐', element: 'Fire', mode: 'Mutable',
    planet: 'Jupiter', dates: 'Nov 22 – Dec 21', color: '#E64A19',
    traits: ['Adventurous', 'Optimistic', 'Honest', 'Philosophical', 'Free-spirited'],
    shadow: ['Blunt', 'Restless', 'Non-committal'],
    compatible: ['Aries', 'Leo', 'Libra', 'Aquarius'],
    lucky: [3, 9],
    description: 'Sagittarius is the explorer of the zodiac — expansive, optimistic, and always seeking the next horizon. Your love of truth and adventure inspires others to see the world with fresh eyes. Your growth comes in discovering that depth and commitment can be their own form of freedom.',
  },
  Capricorn: {
    symbol: '♑', element: 'Earth', mode: 'Cardinal',
    planet: 'Saturn', dates: 'Dec 22 – Jan 19', color: '#37474F',
    traits: ['Disciplined', 'Ambitious', 'Responsible', 'Patient', 'Strategic'],
    shadow: ['Cold', 'Pessimistic', 'Workaholic'],
    compatible: ['Taurus', 'Virgo', 'Scorpio', 'Pisces'],
    lucky: [4, 8],
    description: 'Capricorn is the architect of the zodiac — disciplined, ambitious, and built for the long game. Your capacity for sustained effort and strategic thinking creates lasting achievement that others can only admire. Your growth lies in learning that rest, play, and love are also forms of success.',
  },
  Aquarius: {
    symbol: '♒', element: 'Air', mode: 'Fixed',
    planet: 'Uranus', dates: 'Jan 20 – Feb 18', color: '#00838F',
    traits: ['Visionary', 'Original', 'Humanitarian', 'Independent', 'Intellectual'],
    shadow: ['Detached', 'Rebellious', 'Emotionally distant'],
    compatible: ['Gemini', 'Libra', 'Aries', 'Sagittarius'],
    lucky: [4, 7],
    description: 'Aquarius is the visionary of the zodiac — original, humanitarian, and perpetually ahead of their time. Your ability to see beyond conventions and imagine a better world is a genuine gift to the collective. Your growth comes in bridging the gap between your ideals for humanity and the individuals right in front of you.',
  },
  Pisces: {
    symbol: '♓', element: 'Water', mode: 'Mutable',
    planet: 'Neptune', dates: 'Feb 19 – Mar 20', color: '#4527A0',
    traits: ['Compassionate', 'Intuitive', 'Creative', 'Spiritual', 'Empathetic'],
    shadow: ['Escapist', 'Over-idealistic', 'Boundary-less'],
    compatible: ['Cancer', 'Scorpio', 'Taurus', 'Capricorn'],
    lucky: [7, 3],
    description: 'Pisces is the mystic of the zodiac — boundlessly compassionate, deeply intuitive, and tuned into frequencies others miss entirely. Your imagination and spiritual sensitivity are portals to profound beauty. Your growth lies in anchoring your gifts in the world through healthy boundaries and practical action.',
  },
};

export const elementColors = {
  Fire:  { bg: 'rgba(229,83,53,0.12)',  border: 'rgba(229,83,53,0.4)',  text: '#b94040' },
  Earth: { bg: 'rgba(46,125,50,0.12)',  border: 'rgba(46,125,50,0.4)',  text: '#2E7D32' },
  Air:   { bg: 'rgba(2,119,189,0.12)',  border: 'rgba(2,119,189,0.4)',  text: '#0277BD' },
  Water: { bg: 'rgba(106,27,154,0.12)', border: 'rgba(106,27,154,0.4)', text: '#5E35B1' },
};
